Feature/run tox (#18)
* Misc

* Add test file

* Update test script

* misc

* misc

* misc

* misc

* misc2

* misc3

* misc4

* misc

* misc6

* misc7

* misc8

* misc9

* misc10

* misc

* Skip coverage for now

diff --git a/.github/workflows/ci_master.yml b/.github/workflows/ci_master.yml
--- a/.github/workflows/ci_master.yml
+++ b/.github/workflows/ci_master.yml
@@ -6,37 +6,28 @@ on: [pull_request, push]
 jobs:
   # Set the job key. The key is displayed as the job name
   # when a job name is not provided
-  generic_ci:
-    # Placeholder Job
-    name: Placeholder Job
-    # Set the type of machine to run on
-    runs-on: ubuntu-latest
 
-    steps:
-      # Print something
-      - name: Placeholder printing
-        run: echo "Placeholder printing"
+  # failed_job:
+  #   # The easiest way to deal with that to exclude the job that can faile from the merge checks on github
+  #   # That way the issue will be visible in the PR but can still be merged
+  #   name: Failed Job allowed to fail
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Fail Step
+  #       run: exit 1
 
-      - name: Another Step
-        run: echo "another step"
-
-  failed_job:
-    # The easiest way to deal with that to exclude the job that can faile from the merge checks on github
-    # That way the issue will be visible in the PR but can still be merged
-    name: Failed Job allowed to fail
-    runs-on: ubuntu-latest
-    steps:
-      - name: Fail Step
-        run: exit 1
 
   matrix_expansion_job:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: [3.9, 3.8, 3.7, 3.6]
-        django-db: [SQLITE, POSTGRES]
+        #python-version: [3.9, 3.8, 3.7, 3.6]
+        python-version: [3.9, 3.8]
+        #django-db: [SQLITE, POSTGRES]
+        django-db: [SQLITE]
     name: Python ${{ matrix.python-version }} - Django DB ${{ matrix.django-db }}
     steps:
+      - uses: actions/checkout@v2
       - name: Set Environment Variables
         env:
           DJANGO_DB: ${{ matrix.django-db }}
@@ -48,6 +39,18 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python-version }}
+      - name: Install Dependencies
+        run: pip install coverage tox-gh-actions
+      - name: Run Tests
+        run: |
+          coverage erase
+          # Run tox using the version of Python in `PATH`
+          #tox -e py
+          tox
+      # - name: Handle Coverage
+      #   run: |
+      #     coverage combine --append
+      #     coverage report -m
 
   run_linters:
     runs-on: ubuntu-latest
